packages:
  - '.'
allowBuilds:
  '@parcel/watcher': true
  canvas: false
  esbuild: true
  lmdb: true
  msgpackr-extract: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - lmdb
  - msgpackr-extract
